### ISSUE TITLE
Receiving an error with nio4r v1.0.0 and unable to use nio4r v1.2.0 via bundle update

### ISSUE THREAD

**Issue by espressobeanies** [Netflix/Workflowable#6]
Hi,

I'm getting the exact same error as in this [post](https://github.com/celluloid/nio4r/issues/57). I've tried a 'bundle update nio4r' command to install v1.2.0, however the Workflowable bundle does not accept this version and defaults back to v1.0.0 with the same error again. Is there any workaround to this issue?

Thanks in advance,

**Comment by ahoernecke** [comment]
Hi @espressobeanie,

I'm not sure why you'd need to install nio4r for workflowable. It's not in any of our Gemfiles and we've never seen this issue. Are you sure it's not a different gem that's requiring nio4r?

**Comment by espressobeanies** [comment]
Definitely not. I'm seeing it's listed as a Workflowable dependency here: https://libraries.io/github/Netflix/Workflowable

**Comment by ahoernecke** [comment]
Ahh yeah I see that now. I'm not sure why you're having this issue. Are you trying to use the gem/code directly or through Scumblr or another app? For what it's worth I cloned the code, did a bundle install followed by bundle update nio4r and it used nio4r 1.2.0 with no issue. 

Can you show me what's happening when you try to update nio4r?

**Comment by espressobeanies** [comment]
Through Scumblr. Is Workflowable installed by default by any chance? Yep, well something strange happened. I did a 'bundle install' from my Scumblr install and went back to Workflowable, ran the same command, and that was successful. It appears it accepted nio4r v1.2.1. Strange.

**Comment by ahoernecke** [comment]
Scumblr does include workflowable by default, yes. And that is very strange. Let me know if you think you're good to go or if you're still having issues. Sorry about the confusion.

**Comment by espressobeanies** [comment]
Ah I see. Thanks for letting me know ahoernecke.
